services:
  evrinoma.fake.manager:
    class: Evrinoma\FakeBundle\Manager\FakeManager

  Evrinoma\FakeBundle\Manager\FakeManager:
    alias: evrinoma.fake.manager

  evrinoma.fake.api.controller:
    class: Evrinoma\FakeBundle\Controller\FakeApiController

  Evrinoma\FakeBundle\Controller\FakeApiController:
    alias: evrinoma.fake.api.controller
    public: true

